apiVersion: v1
kind: Namespace
metadata:
  name: production

---

apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: production
type: Opaque
data:
  MY_SECRET: T24zSDF0b3JMM3NT  # This is 'On3H1torL3sS' base64 encoded

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: app-container
        image: rdicidr-app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: MY_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: MY_SECRET

---

apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: production
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 3000
  type: NodePort
